apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vista-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vista.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
