"""Tests for the host DNS helper.

Duplicated in `dev_mcp_server`, where the module under test is duplicated too. A change
here belongs in both.
"""

import logging

import pytest

from vista_mcp_server.lib import dns

pytestmark = pytest.mark.unit

# Trimmed from a real `scutil --dns`: IPv6 resolvers ahead of the IPv4 ones,
# mDNS resolvers carrying no nameserver at all, and a scoped section repeating
# everything the unscoped one already said.
SCUTIL = """DNS configuration

resolver #1
  search domain[0] : ornl.gov
  nameserver[0] : 2620:0:2b33:500f::afea
  nameserver[1] : 10.1.11.166
  nameserver[2] : 10.1.11.168
  if_index : 12 (en0)
  flags    : Request A records, Request AAAA records

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : ornl.gov
  nameserver[0] : 2620:0:2b33:500f::afea
  nameserver[1] : 10.1.11.166
  nameserver[2] : 10.1.11.168
  if_index : 12 (en0)
  flags    : Scoped, Request A records, Request AAAA records
"""

RESOLV_CONF = """# Generated by NetworkManager
; a semicolon is a comment too
search ornl.gov sns.gov
nameserver 10.1.11.166
nameserver 2620:0:2b33:500f::afea
nameserver 10.1.11.168
options edns0
"""


class TestParsing:
    def test_scutil_keeps_ipv4_in_order_and_ignores_the_scoped_repeat(self):
        assert dns.parse_scutil_dns(SCUTIL) == ("10.1.11.166", "10.1.11.168")

    def test_resolv_conf_keeps_ipv4_in_order_and_skips_comments(self):
        assert dns.parse_resolv_conf(RESOLV_CONF) == ("10.1.11.166", "10.1.11.168")

    @pytest.mark.parametrize(
        "text",
        [
            "",
            "DNS configuration\n\nresolver #1\n  domain : local\n  options : mdns\n",
            "# nothing but comments\nsearch ornl.gov\noptions edns0\n",
            "nameserver 2620:0:2b33:500f::afea\n",
            "nameserver not-an-address\n",
        ],
    )
    def test_nothing_usable_parses_as_nothing(self, text):
        assert dns.parse_scutil_dns(text) == ()
        assert dns.parse_resolv_conf(text) == ()


class TestHostNameservers:
    def test_darwin_reads_the_system_configuration(self, monkeypatch):
        monkeypatch.setattr(dns.sys, "platform", "darwin")
        monkeypatch.setattr(dns, "_read_scutil", lambda: SCUTIL)
        monkeypatch.setattr(
            dns, "_read_resolv_conf", lambda: pytest.fail("read resolv.conf on darwin")
        )

        assert dns.host_nameservers() == ("10.1.11.166", "10.1.11.168")

    def test_linux_reads_resolv_conf(self, monkeypatch):
        monkeypatch.setattr(dns.sys, "platform", "linux")
        monkeypatch.setattr(dns, "_read_resolv_conf", lambda: RESOLV_CONF)
        monkeypatch.setattr(
            dns, "_read_scutil", lambda: pytest.fail("ran scutil off darwin")
        )

        assert dns.host_nameservers() == ("10.1.11.166", "10.1.11.168")

    def test_empty_configuration_falls_back_and_says_so(self, monkeypatch, caplog):
        monkeypatch.setattr(dns.sys, "platform", "linux")
        monkeypatch.setattr(dns, "_read_resolv_conf", lambda: "search ornl.gov\n")

        with caplog.at_level(logging.WARNING):
            assert dns.host_nameservers() == dns.FALLBACK_NAMESERVERS

        assert "1.1.1.1, 8.8.8.8" in caplog.text

    def test_unreadable_configuration_falls_back_and_says_so(self, monkeypatch, caplog):
        def explode():
            raise OSError("no such file")

        monkeypatch.setattr(dns.sys, "platform", "linux")
        monkeypatch.setattr(dns, "_read_resolv_conf", explode)

        with caplog.at_level(logging.WARNING):
            assert dns.host_nameservers() == dns.FALLBACK_NAMESERVERS

        assert "Could not read the host's DNS configuration" in caplog.text
